name: Deploy to S3 and Cloudfront

on:
  workflow_dispatch:
  
env:
  APP_RELEASE_VERSION: 0.0.8 # Should come from input args
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: app-habitica-equipment-tracker
  AWS_CLOUDFRONT_DISTRIBUTION: E3BHNXZYW712AG

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download release
      run: curl -sL -o build.zip "https://github.com/Blockost/habitica-equipment-tracker/releases/download/$APP_RELEASE_VERSION/build.zip" && unzip build.zip -d ./build

    - name: Remove existing files from S3
      run: aws s3 rm "s3://$S3_BUCKET_NAME" --recursive
    
    - name: Upload to S3
      run: aws s3 cp ./build "s3://$S3_BUCKET_NAME/" --recursive

    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION --paths '/*'
